services:
  - type: web
    name: startup-connector
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: MONGODB_URI
        value: your-mongodb-connection-string-here